# Generated by Django 5.1.3 on 2024-12-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=255)),
                ('student_program_id', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('cluster_name', models.CharField(max_length=255)),
                ('cluster_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('hour', models.IntegerField()),
                ('is_present', models.BooleanField()),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('staff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('time_table_id', models.CharField(blank=True, max_length=255, null=True)),
                ('student_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subject')),
            ],
        ),
    ]
